apiVersion: skaffold/v4beta6
kind: Config
build:
   artifacts:
      - image: chihtengma416/auth
        context: auth
        sync:
           manual:
              - src: "src/**/*.ts"
                dest: .
        docker:
           dockerfile: Dockerfile
      - image: chihtengma416/client
        context: client
        sync:
           manual:
              - src: "**/*.js"
                dest: .
        docker:
           dockerfile: Dockerfile
   local:
      push: false
   # googleCloudBuild:
   #    projectId: ticketing-dev-397117
manifests:
   rawYaml:
      - ./infra/k8s/*
deploy:
   kubectl: {}
# us.gcr.io/ticketing-dev-397117/auth
# us.gcr.io/ticketing-dev-397117/client
